### PR TITLE
Bump to libocr master 2271752fa829

### PR DESCRIPTION
**Pull request by samsondav**

### CODE REVIEW

**Review by jmank88 — DISMISSED** [review]

**Comment by bolekk** [comment]
I think you also need to bump chainlink core to something much fresher than @v2.2.0-mercury-20230608.0.20230610030307-281eedc27b1f

**Review by bolekk — CHANGES_REQUESTED** [review]
@samsondav the old core dep here is no longer compatible with newest relay - you need to bump core too.

**Comment by bolekk** [comment]
hmmmm, we might need to wait for this https://github.com/smartcontractkit/chainlink/pull/10054 and then update core again...? I'm confused about the message in failures here but let's do that and see.

**Comment by bolekk** [comment]
Bumped dep versions again and now getting a completely different error :) @aalu1418 help please!

146.7 common/test_common.go:97:27: undefined: client.Chainlink
146.7 common/test_common.go:214:54: undefined: client.Chainlink
146.7 common/common.go:123:95: undefined: client.Chainlink
146.7 common/common.go:128:47: cannot use ChainlinkNodes (variable of type []*"github.com/smartcontractkit/chainlink/integration-tests/client".ChainlinkK8sClient) as []*"github.com/smartcontractkit/chainlink/integration-tests/client".ChainlinkClient value in argument to client.CreateNodeKeysBundle

**Comment by aalu1418** [comment]
> Bumped dep versions again and now getting a completely different error :) @aalu1418 help please!
> 
> 146.7 common/test_common.go:97:27: undefined: client.Chainlink 146.7 common/test_common.go:214:54: undefined: client.Chainlink 146.7 common/common.go:123:95: undefined: client.Chainlink 146.7 common/common.go:128:47: cannot use ChainlinkNodes (variable of type []_"github.com/smartcontractkit/chainlink/integration-tests/client".ChainlinkK8sClient) as []_"github.com/smartcontractkit/chainlink/integration-tests/client".ChainlinkClient value in argument to client.CreateNodeKeysBundle

@smickovskid are the starknet e2e tests just in a broken state for starknet?

**Comment by archseer** [comment]
Code should build but I'm doing maintenance in my PR, the devnet now expects much never cairo versions: https://github.com/smartcontractkit/chainlink-starknet/pull/310

**Comment by archseer** [comment]
Might need this cherry-pick: https://github.com/smartcontractkit/chainlink-starknet/pull/310/commits/579aa3d5a845d5b9f922fd83b4852b631f269770

**Comment by aalu1418** [comment]
will close this PR once this PR is merged: https://github.com/smartcontractkit/chainlink-starknet/pull/317
(duplicated and e2e tests fixed in the other PR)

**Pull request closed without merging**
