### PR TITLE
bump juno to v0.12.2

### PR DESCRIPTION
**Pull request by jmank88**

### CODE REVIEW

**Comment by augustbleeds** [comment]
Thanks, is this just cause? Or is there some dependency in the core that requires this bump

**Comment by jmank88** [comment]
> Thanks, is this just cause? Or is there some dependency in the core that requires this bump

I was hoping this would have a cascading effect that fixes the sourcegraph issues, but starknet.go is not compatible with this version anyways.

**Comment by augustbleeds** [comment]
@jmank88 Nethermind recently made a code change to update starknet.go based off our request to bump juno. 

https://github.com/NethermindEth/starknet.go/pull/625

They said it'll be released in their next version

**Comment by jmank88** [comment]
Updated to the latest starknet.go version, but now this forces us to upgrade geth, so we're blocked on https://github.com/smartcontractkit/chainlink/pull/11809.

**Comment by jmank88** [comment]
Why was this closed? Please re-open @chray-zhang

**Comment by chray-zhang** [comment]
@jmank88 

I accidentally erased some of[ chainlink-starknet's origin history](https://chainlink-core.slack.com/archives/C0205CH9PH8/p1732571859763359). Do you have a local branch you can force push up? If not I created a new PR with your commit: https://github.com/smartcontractkit/chainlink-starknet/pull/555

Can you let me know if that's the change?

**Comment by jmank88** [comment]
> @jmank88
> 
> I accidentally erased some of[ chainlink-starknet's origin history](https://chainlink-core.slack.com/archives/C0205CH9PH8/p1732571859763359). Do you have a local branch you can force push up? If not I created a new PR with your commit: #555
> 
> Can you let me know if that's the change?

That is probably good enough :+1:

**Pull request closed without merging**
